CREATE OR REPLACE PACKAGE DLY_RTS_DMMY_DT_GNRTR AS

PROCEDURE APPS_INITIALIZE;
PROCEDURE INSERT_DUMMY_RECORD(p_from_currency VARCHAR2, p_to_currency VARCHAR2, p_file_name VARCHAR2);
PROCEDURE INSERT_DUMMY_RECORDS;
PROCEDURE main_method;

END DLY_RTS_DMMY_DT_GNRTR;