-- This Oracle SQL script to create table with name as XXGL_DAILY_RATES_INTF_STG. 
-- It includes columns FROM_CONVERSION_DATE, TO_CONVERSION_DATE, TO_CURRENCY, 
-- FROM_CURRENCY, MODE_FLAG, CONVERSION_RATE, USER_CONVERSION_TYPE, CREATION_DATE, 
-- CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY and REQUEST_ID. 
-- Data type, length and whether or not the null value is allowed for these columns 
-- would be same as respective columns in GL_DAILY_RATES_INTERFACE table. 
-- This script should run as XXELS user.

CREATE TABLE XXGL_DAILY_RATES_INTF_STG
(
  FROM_CONVERSION_DATE DATE,
  TO_CONVERSION_DATE DATE,
  TO_CURRENCY VARCHAR2(15 BYTE),
  FROM_CURRENCY VARCHAR2(15 BYTE),
  MODE_FLAG VARCHAR2(1 BYTE),
  CONVERSION_RATE NUMBER,
  USER_CONVERSION_TYPE VARCHAR2(15 BYTE),
  CREATION_DATE DATE,
  CREATED_BY NUMBER,
  LAST_UPDATE_DATE DATE,
  LAST_UPDATED_BY NUMBER,
  REQUEST_ID NUMBER
);

-- Following statement provides all grants on XXGL_DAILY_RATES_INTF_STG table to APPS user
GRANT SELECT, INSERT, UPDATE, DELETE ON XXGL_DAILY_RATES_INTF_STG TO APPS;