-- Create sequence XXGL_DAILY_RATES_INTF_STG_S with start value as 1 and increment by 1 and no cache and no cycle
CREATE SEQUENCE XXGL_DAILY_RATES_INTF_STG_S START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- This Oracle SQL script to create table with name as XXGL_DAILY_RATES_INTF_STG. 
--
-- It includes following columns 
--  01. FROM_CONVERSION_DATE
--  02. TO_CONVERSION_DATE
--  03. TO_CURRENCY
--  04. FROM_CURRENCY
--  05. MODE_FLAG
--  06. CONVERSION_RATE
--  07. USER_CONVERSION_TYPE
--  08. CREATION_DATE 
--  09. CREATED_BY 
--  10. LAST_UPDATE_DATE
--  11. LAST_UPDATED_BY
--  12. LAST_UPDATE_LOGIN
--  13. REQUEST_ID
--  14. FILE_NAME
--  15. LOAD_DATE
--  16. RECORD_ID
--
-- Note:
--  1. Data type, length and whether or not the null value is allowed for these columns 
--     are same as respective columns in GL_DAILY_RATES_INTERFACE table 
--
--  2. Values of MODE_FLAG are to be restricted as I or U
--
--  3. Value of USER_CONVERSION_TYPE will be Corporate
--
--  4. CREATION_DATE, LAST_UPDATE_DATE, LOAD_DATE value is defaulted as SYSDATE 
--
--  5. RECORD_ID is a primary key column and its value should be defaulted as  XXGL_DAILY_RATES_INTF_STG_S.NEXTVAL

CREATE TABLE XXGL_DAILY_RATES_INTF_STG
(
  FROM_CONVERSION_DATE DATE,
  TO_CONVERSION_DATE DATE,
  TO_CURRENCY VARCHAR2(15),
  FROM_CURRENCY VARCHAR2(15),
  MODE_FLAG VARCHAR2(1),
  CONVERSION_RATE NUMBER(20,6),
  USER_CONVERSION_TYPE VARCHAR2(15),
  CREATION_DATE DATE DEFAULT SYSDATE,
  CREATED_BY NUMBER(15),
  LAST_UPDATE_DATE DATE DEFAULT SYSDATE,
  LAST_UPDATED_BY NUMBER(15),
  LAST_UPDATE_LOGIN NUMBER(15),
  REQUEST_ID NUMBER(15),
  FILE_NAME VARCHAR2(100),
  LOAD_DATE DATE DEFAULT SYSDATE,
  RECORD_ID NUMBER(15) DEFAULT XXGL_DAILY_RATES_INTF_STG_S.NEXTVAL,
  CONSTRAINT XXGL_DAILY_RATES_INTF_STG_PK PRIMARY KEY (RECORD_ID)
);

-- This statement gives all grants on XXGL_DAILY_RATES_INTF_STG table to APPS user
GRANT ALL ON XXGL_DAILY_RATES_INTF_STG TO APPS;
